import java.util.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JButton;
public class avaliacaoLivroInterface extends javax.swing.JPanel {

    ArrayList<Livro> livros;
    ArrayList<Exemplar> exemplares;
    ArrayList<Emprestimo> emprestimos;
    ArrayList<Usuario> usuarios;
    ArrayList<Avaliacao> avaliacoes;
    String comentario, IDLivroAva;
    float estrelas;
    /**
     * Creates new form avaliacaoLivroInterface
     */
    public avaliacaoLivroInterface(ArrayList<Livro> livros, ArrayList<Exemplar> exemplares, ArrayList<Emprestimo> emprestimos, ArrayList<Usuario> usuarios, ArrayList<Avaliacao> avaliacoes) {
        initComponents();
        this.livros = livros;
        this.exemplares = exemplares;
        this.emprestimos = emprestimos;
        this.usuarios = usuarios;
        this.avaliacoes = avaliacoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postarAvaliacaoBotao = new javax.swing.JButton();
        IDLivroTexto = new javax.swing.JLabel();
        comentarioTexto = new javax.swing.JLabel();
        campoIDLivro = new javax.swing.JTextField();
        campoComentario = new javax.swing.JTextField();
        estrelasTexto = new javax.swing.JLabel();
        estrela1Imagem = new javax.swing.JLabel();
        campoEstrelas = new javax.swing.JTextField();

        postarAvaliacaoBotao.setText("Postar avaliação");
        postarAvaliacaoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postarAvaliacaoBotaoActionPerformed(evt);
            }
        });

        IDLivroTexto.setText("ID do livro: ");

        comentarioTexto.setText("Comentário (opcional): ");

        campoIDLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDLivroActionPerformed(evt);
            }
        });

        estrelasTexto.setText("Estrelas:");

        estrela1Imagem.setText("jLabel1");

        campoEstrelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstrelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDLivroTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoIDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estrelasTexto)
                        .addGap(18, 18, 18)
                        .addComponent(campoEstrelas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(comentarioTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(postarAvaliacaoBotao)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(estrela1Imagem)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(estrela1Imagem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLivroTexto)
                    .addComponent(campoIDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estrelasTexto)
                    .addComponent(campoEstrelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comentarioTexto))
                .addGap(18, 18, 18)
                .addComponent(postarAvaliacaoBotao)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDLivroActionPerformed

    private void postarAvaliacaoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postarAvaliacaoBotaoActionPerformed
        IDLivroAva = campoIDLivro.getText();
        estrelas = Float.parseFloat(campoEstrelas.getText());
        comentario = campoComentario.getText();
        for(int i = 0; i<livros.size(); i++){
            if(IDLivroAva.equals(livros.get(i).getIDLivro())){
                Avaliacao novaAvaliacao = new Avaliacao(estrelas, comentario, IDLivroAva);
                avaliacoes.add(novaAvaliacao);
                JOptionPane.showMessageDialog(null, "Avaliação postada com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Livro não encontrado no acervo!");
            }
        }
    }//GEN-LAST:event_postarAvaliacaoBotaoActionPerformed

    private void campoEstrelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstrelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEstrelasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLivroTexto;
    private javax.swing.JTextField campoComentario;
    private javax.swing.JTextField campoEstrelas;
    private javax.swing.JTextField campoIDLivro;
    private javax.swing.JLabel comentarioTexto;
    private javax.swing.JLabel estrela1Imagem;
    private javax.swing.JLabel estrelasTexto;
    private javax.swing.JButton postarAvaliacaoBotao;
    // End of variables declaration//GEN-END:variables
}
