import java.util.*;
import javax.swing.JOptionPane;
public class cadastrarLivroInterface extends javax.swing.JFrame {

    ArrayList<Livro> livros;
    ArrayList<Exemplar> exemplares;
    ArrayList<Emprestimo> emprestimos;
    ArrayList<Usuario> usuarios;
    String IDLivro, titulo, autor, genero, sinopse;
    int numExemplares, anoPubli;
    /**
     * Creates new form cadastrarLivroInterface
     */
    public cadastrarLivroInterface(ArrayList<Livro> livros, ArrayList<Exemplar> exemplares, ArrayList<Emprestimo> emprestimos, ArrayList<Usuario> usuarios) {
        initComponents();
        this.livros = livros;
        this.exemplares = exemplares;
        this.emprestimos = emprestimos;
        this.usuarios = usuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloInterface = new javax.swing.JLabel();
        campoIDLivro = new javax.swing.JTextField();
        campoTituloLivro = new javax.swing.JTextField();
        campoAutorLivro = new javax.swing.JTextField();
        campoGeneroLivro = new javax.swing.JTextField();
        campoSinopse = new javax.swing.JTextField();
        cadastrarLivroBotaoInterface = new javax.swing.JButton();
        campoAnoPubli = new javax.swing.JTextField();
        campoNumExem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloInterface.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        tituloInterface.setText("Biblio+");
        getContentPane().add(tituloInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(939, 6, -1, -1));

        campoIDLivro.setToolTipText("");
        campoIDLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDLivroActionPerformed(evt);
            }
        });
        getContentPane().add(campoIDLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 230, 40));

        campoTituloLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloLivroActionPerformed(evt);
            }
        });
        getContentPane().add(campoTituloLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 230, 40));
        getContentPane().add(campoAutorLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 230, 40));

        campoGeneroLivro.setToolTipText("");
        getContentPane().add(campoGeneroLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 230, 30));
        getContentPane().add(campoSinopse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 350, 100));

        cadastrarLivroBotaoInterface.setContentAreaFilled(false);
        cadastrarLivroBotaoInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLivroBotaoInterfaceActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarLivroBotaoInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 140, 40));

        campoAnoPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoPubliActionPerformed(evt);
            }
        });
        getContentPane().add(campoAnoPubli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 242, 200, 30));

        campoNumExem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumExemActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumExem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 272, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroLivro.png"))); // NOI18N
        jLabel1.setText("interfaceGUI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDLivroActionPerformed

    private void campoTituloLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloLivroActionPerformed

    private void cadastrarLivroBotaoInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLivroBotaoInterfaceActionPerformed
        IDLivro = campoIDLivro.getText();
        titulo = campoTituloLivro.getText();
        autor = campoAutorLivro.getText();
        genero = campoGeneroLivro.getText();
        sinopse = campoSinopse.getText();
        numExemplares = Integer.parseInt(campoNumExem.getText());
        anoPubli = Integer.parseInt(campoAnoPubli.getText());
        
        Livro livroNovo = new Livro(IDLivro, titulo, autor, genero, sinopse, numExemplares, anoPubli);
        for(int l = 0; l<numExemplares; l++){
            Exemplar novoExemplar = new Exemplar();
            livroNovo.getExemplares().add(novoExemplar);
        }
        LivroDAO livroConsultar = new LivroDAO();
        livroConsultar.inserirLivro(livroNovo);
    }//GEN-LAST:event_cadastrarLivroBotaoInterfaceActionPerformed

    private void campoAnoPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoPubliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoPubliActionPerformed

    private void campoNumExemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumExemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumExemActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarLivroInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarLivroInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarLivroInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarLivroInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarLivroInterface().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarLivroBotaoInterface;
    private javax.swing.JTextField campoAnoPubli;
    private javax.swing.JTextField campoAutorLivro;
    private javax.swing.JTextField campoGeneroLivro;
    private javax.swing.JTextField campoIDLivro;
    private javax.swing.JTextField campoNumExem;
    private javax.swing.JTextField campoSinopse;
    private javax.swing.JTextField campoTituloLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tituloInterface;
    // End of variables declaration//GEN-END:variables
}
