/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author genis
 */
public class consultarInterface extends javax.swing.JPanel {

    /**
     * Creates new form consultarInterface
     */
    public consultarInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultarUsuariosBotao = new javax.swing.JButton();
        consultarLivrosBotao = new javax.swing.JButton();
        consultarExemplaresBotao = new javax.swing.JButton();
        consultarEmprBotao = new javax.swing.JButton();
        consultarAvaliacoesBotao = new javax.swing.JButton();

        consultarUsuariosBotao.setText("Consultar Usuários");
        consultarUsuariosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuariosBotaoActionPerformed(evt);
            }
        });

        consultarLivrosBotao.setText("Consultar Livros");
        consultarLivrosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarLivrosBotaoActionPerformed(evt);
            }
        });

        consultarExemplaresBotao.setText("Consultar Exemplares");
        consultarExemplaresBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarExemplaresBotaoActionPerformed(evt);
            }
        });

        consultarEmprBotao.setText("Consultar Empréstimos");
        consultarEmprBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEmprBotaoActionPerformed(evt);
            }
        });

        consultarAvaliacoesBotao.setText("Consultar Avaliações");
        consultarAvaliacoesBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAvaliacoesBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarExemplaresBotao)
                    .addComponent(consultarUsuariosBotao)
                    .addComponent(consultarLivrosBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultarEmprBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarAvaliacoesBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(consultarUsuariosBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarLivrosBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarExemplaresBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(consultarEmprBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarAvaliacoesBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultarEmprBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEmprBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarEmprBotaoActionPerformed

    private void consultarUsuariosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuariosBotaoActionPerformed
        UsuarioDAO usuarioConsultar = new UsuarioDAO();
        usuarioConsultar.consultarTudo();
    }//GEN-LAST:event_consultarUsuariosBotaoActionPerformed

    private void consultarLivrosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLivrosBotaoActionPerformed
        LivroDAO livroConsultar = new LivroDAO();
        livroConsultar.consultarTudo();
    }//GEN-LAST:event_consultarLivrosBotaoActionPerformed

    private void consultarExemplaresBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarExemplaresBotaoActionPerformed
        ExemplarDAO exemplarConsultar = new ExemplarDAO();
        exemplarConsultar.consultarTudo();
    }//GEN-LAST:event_consultarExemplaresBotaoActionPerformed

    private void consultarAvaliacoesBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAvaliacoesBotaoActionPerformed
        AvaliacaoDAO avaliacaoConsultar = new AvaliacaoDAO();
        avaliacaoConsultar.consultarTudo();
    }//GEN-LAST:event_consultarAvaliacoesBotaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarAvaliacoesBotao;
    private javax.swing.JButton consultarEmprBotao;
    private javax.swing.JButton consultarExemplaresBotao;
    private javax.swing.JButton consultarLivrosBotao;
    private javax.swing.JButton consultarUsuariosBotao;
    // End of variables declaration//GEN-END:variables
}
