import java.util.*;
import javax.swing.JOptionPane;

public class loginInterface extends javax.swing.JPanel {

    ArrayList<Livro> livros = new ArrayList<Livro>();
    ArrayList<Exemplar> exemplares = new ArrayList<Exemplar>();
    ArrayList<Emprestimo> emprestimos = new ArrayList<Emprestimo>();
    ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
    ArrayList<Avaliacao> avaliacoes = new ArrayList<Avaliacao>();
    /**
     * Creates new form loginInterface
     */
    public loginInterface(ArrayList<Livro> livros, ArrayList<Exemplar> exemplares, ArrayList<Emprestimo> emprestimos, ArrayList<Usuario> usuarios, ArrayList<Avaliacao> avaliacoes) {
        initComponents();
        this.livros = livros;
        this.exemplares = exemplares;
        this.emprestimos = emprestimos;
        this.usuarios = usuarios;
        this.avaliacoes = avaliacoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoEmail = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        logarBotao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 170, 50));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 252, 170, 50));

        logarBotao.setContentAreaFilled(false);
        logarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarBotaoActionPerformed(evt);
            }
        });
        add(logarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 343, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login(1400 x 1200 px).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        
    }//GEN-LAST:event_campoEmailActionPerformed

    private void logarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarBotaoActionPerformed
        String emailVerifica = campoEmail.getText();
        String senhaVerifica = new String(campoSenha.getPassword());
        for(int i = 0; i<usuarios.size(); i++){
            if (emailVerifica.equalsIgnoreCase(usuarios.get(i).getEmail()) && senhaVerifica.equals(usuarios.get(i).getSenha())) {
                JOptionPane.showMessageDialog(null, "Login realizado com sucesso!");
                MenuPrincipalPosLogin menuPosLogin = new MenuPrincipalPosLogin(livros, exemplares, emprestimos, usuarios, avaliacoes);
                menuPosLogin.setVisible(true);
            }
            else if(emailVerifica.equals("admin@gmail.com") && senhaVerifica.equals("admin123")){
                JOptionPane.showMessageDialog(null, "Login do administrador realizado com sucesso!");
                MenuPrincipalPosLoginAdmin menuAdmin = new MenuPrincipalPosLoginAdmin(livros, exemplares, emprestimos, usuarios, avaliacoes);
                menuAdmin.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "E-mail ou senha incorretos!");
            }
        }
    }//GEN-LAST:event_logarBotaoActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoEmail;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logarBotao;
    // End of variables declaration//GEN-END:variables
}
