import java.util.*;
import javax.swing.JOptionPane;
public class MenuPrincipal extends javax.swing.JFrame {
    
    ArrayList<Livro> livros = new ArrayList<Livro>();
    ArrayList<Exemplar> exemplares = new ArrayList<Exemplar>();
    ArrayList<Emprestimo> emprestimos = new ArrayList<Emprestimo>();
    ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
    ArrayList<Avaliacao> avaliacoes = new ArrayList<Avaliacao>();
    Sistema sistema = new Sistema();
    String livroPesquisaTitulo, livroPesquisaAutor, livroPesquisaGenero;
    /**
     * Creates new form Interfac
     */
    public MenuPrincipal(ArrayList<Livro> livros, ArrayList<Exemplar> exemplares, ArrayList<Emprestimo> emprestimos, ArrayList<Usuario> usuarios, ArrayList<Avaliacao> avaliacoes) {
        initComponents();
        sistema.cadastrarAdmin();
        this.livros = livros;
        this.exemplares = exemplares;
        this.emprestimos = emprestimos;
        this.usuarios = usuarios;
        this.avaliacoes = avaliacoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloInterface = new javax.swing.JLabel();
        pesquisarTituloBotao = new javax.swing.JButton();
        pesquisarAutorBotao = new javax.swing.JButton();
        cadastrarBotaoPInterface = new javax.swing.JButton();
        logarBotaoPInterface = new javax.swing.JButton();
        pesquisarGeneroBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloInterface.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        tituloInterface.setText("Biblio+");

        pesquisarTituloBotao.setText("Pesquisar obra por título");
        pesquisarTituloBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTituloBotaoActionPerformed(evt);
            }
        });

        pesquisarAutorBotao.setText("Pesquisar autores");
        pesquisarAutorBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAutorBotaoActionPerformed(evt);
            }
        });

        cadastrarBotaoPInterface.setText("Cadastrar usuário");
        cadastrarBotaoPInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBotaoPInterfaceActionPerformed(evt);
            }
        });

        logarBotaoPInterface.setText("Logar");
        logarBotaoPInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarBotaoPInterfaceActionPerformed(evt);
            }
        });

        pesquisarGeneroBotao.setText("Pesquisar obra por gênero");
        pesquisarGeneroBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarGeneroBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarBotaoPInterface)
                            .addComponent(tituloInterface)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(logarBotaoPInterface))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(pesquisarAutorBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(pesquisarTituloBotao)
                        .addGap(26, 26, 26)
                        .addComponent(pesquisarGeneroBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloInterface)
                .addGap(31, 31, 31)
                .addComponent(logarBotaoPInterface)
                .addGap(18, 18, 18)
                .addComponent(cadastrarBotaoPInterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarAutorBotao)
                    .addComponent(pesquisarTituloBotao)
                    .addComponent(pesquisarGeneroBotao))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarTituloBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTituloBotaoActionPerformed
        livroPesquisaTitulo = JOptionPane.showInputDialog(null, "Insira o título que deseja pesquisar.");
        for (int i = 0; i < livros.size(); i++) {
            if (livroPesquisaTitulo.equalsIgnoreCase(livros.get(i).getTitulo())) {
                JOptionPane.showMessageDialog(null, "Livro presente no acervo!");
                livros.get(i).exibirLivro();
            }
            else{
                JOptionPane.showMessageDialog(null, "Livro não encontrado no acervo!");
            }
        }
    }//GEN-LAST:event_pesquisarTituloBotaoActionPerformed

    private void logarBotaoPInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarBotaoPInterfaceActionPerformed
        loginInterface logar = new loginInterface(livros, exemplares, emprestimos, usuarios, avaliacoes);
        logar.setVisible(true);
    }//GEN-LAST:event_logarBotaoPInterfaceActionPerformed

    private void cadastrarBotaoPInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBotaoPInterfaceActionPerformed
        cadastroInterface cadastrar = new cadastroInterface(livros, exemplares, emprestimos, usuarios, avaliacoes);
        cadastrar.setVisible(true);
    }//GEN-LAST:event_cadastrarBotaoPInterfaceActionPerformed

    private void pesquisarAutorBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAutorBotaoActionPerformed
        livroPesquisaAutor = JOptionPane.showInputDialog(null, "Insira o autor que deseja pesquisar.");
        for (int i = 0; i < livros.size(); i++) {
            if (livroPesquisaAutor.equalsIgnoreCase(livros.get(i).getAutor())) {
                System.out.println(livros.get(i).getTitulo());
                JOptionPane.showMessageDialog(null, "Autor presente no acervo!");
                livros.get(i).exibirLivro();
            }
        }
    }//GEN-LAST:event_pesquisarAutorBotaoActionPerformed

    private void pesquisarGeneroBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarGeneroBotaoActionPerformed
        livroPesquisaGenero = JOptionPane.showInputDialog(null, "Insira o gênero literário que deseja pesquisar.");
        for (int i = 0; i < livros.size(); i++) {
            if (livroPesquisaTitulo.equalsIgnoreCase(livros.get(i).getGenero())) {
                JOptionPane.showMessageDialog(null, "Gênero literário presente no acervo!");
                livros.get(i).exibirLivro();
            }
            else{
                JOptionPane.showMessageDialog(null, "GÊnero literário não encontrado no acervo!");
            }
        }
    }//GEN-LAST:event_pesquisarGeneroBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarBotaoPInterface;
    private javax.swing.JButton logarBotaoPInterface;
    private javax.swing.JButton pesquisarAutorBotao;
    private javax.swing.JButton pesquisarGeneroBotao;
    private javax.swing.JButton pesquisarTituloBotao;
    private javax.swing.JLabel tituloInterface;
    // End of variables declaration//GEN-END:variables
}
