import java.util.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;
public class MenuPrincipalPosLogin extends javax.swing.JFrame {

    ArrayList<Livro> livros;
    ArrayList<Exemplar> exemplares;
    ArrayList<Emprestimo> emprestimos;
    ArrayList<Usuario> usuarios;
    ArrayList<Avaliacao> avaliacoes;
    String livroPesquisaAutor, livroPesquisaTitulo, livroPesquisaGenero;
    String IDUsuarioEmpr, IDEmprestimo, IDEmprVerifica, IDLivroEmpr, IDUsuarioReserva, IDlivroReserva, senhaVerifica;
    LocalDate dataVencimento;
    /**
     * Creates new form MenuPrincipalPosLogin
     */
    public MenuPrincipalPosLogin(ArrayList<Livro> livros, ArrayList<Exemplar> exemplares, ArrayList<Emprestimo> emprestimos, ArrayList<Usuario> usuarios, ArrayList<Avaliacao> avaliacoes) {
        initComponents();
        this.livros = livros;
        this.exemplares = exemplares;
        this.emprestimos = emprestimos;
        this.usuarios = usuarios;
        this.avaliacoes = avaliacoes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloInterface = new javax.swing.JLabel();
        avaliarLivroBotao = new javax.swing.JButton();
        realizarEmprestimoBotao = new javax.swing.JButton();
        reservarLivroBotao = new javax.swing.JButton();
        renovarEmprestimoBotao = new javax.swing.JButton();
        pesquisarTituloBotao = new javax.swing.JButton();
        pesquisarAutorBotao = new javax.swing.JButton();
        cancelarEmprestimoBotao = new javax.swing.JButton();
        cancelarReservaBotao = new javax.swing.JButton();
        pesquisarGeneroBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloInterface.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        tituloInterface.setText("Biblio+");

        avaliarLivroBotao.setText("Avaliar livro");
        avaliarLivroBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarLivroBotaoActionPerformed(evt);
            }
        });

        realizarEmprestimoBotao.setText("Realizar empréstimo");
        realizarEmprestimoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarEmprestimoBotaoActionPerformed(evt);
            }
        });

        reservarLivroBotao.setText("Reservar exemplar");
        reservarLivroBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarLivroBotaoActionPerformed(evt);
            }
        });

        renovarEmprestimoBotao.setText("Renovar empréstimo");
        renovarEmprestimoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renovarEmprestimoBotaoActionPerformed(evt);
            }
        });

        pesquisarTituloBotao.setText("Pesquisar obra por título");
        pesquisarTituloBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarTituloBotaoActionPerformed(evt);
            }
        });

        pesquisarAutorBotao.setText("Pesquisar obra por autor");
        pesquisarAutorBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAutorBotaoActionPerformed(evt);
            }
        });

        cancelarEmprestimoBotao.setText("Cancelar empréstimo");
        cancelarEmprestimoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEmprestimoBotaoActionPerformed(evt);
            }
        });

        cancelarReservaBotao.setText("Cancelar reserva");
        cancelarReservaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarReservaBotaoActionPerformed(evt);
            }
        });

        pesquisarGeneroBotao.setText("Pesquisar obra por gênero");
        pesquisarGeneroBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarGeneroBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avaliarLivroBotao)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(renovarEmprestimoBotao)
                            .addComponent(reservarLivroBotao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarReservaBotao)
                            .addComponent(cancelarEmprestimoBotao)))
                    .addComponent(realizarEmprestimoBotao))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisarAutorBotao, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(pesquisarGeneroBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesquisarTituloBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(tituloInterface)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloInterface)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realizarEmprestimoBotao)
                    .addComponent(pesquisarTituloBotao))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(renovarEmprestimoBotao)
                            .addComponent(cancelarEmprestimoBotao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reservarLivroBotao)
                            .addComponent(cancelarReservaBotao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(pesquisarGeneroBotao)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avaliarLivroBotao)
                    .addComponent(pesquisarAutorBotao))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliarLivroBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarLivroBotaoActionPerformed
        avaliacaoLivroInterface avaliaInterface = new avaliacaoLivroInterface(livros, exemplares, emprestimos, usuarios, avaliacoes);
    }//GEN-LAST:event_avaliarLivroBotaoActionPerformed

    private void pesquisarTituloBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarTituloBotaoActionPerformed
        livroPesquisaTitulo = JOptionPane.showInputDialog(null, "Insira o título que deseja pesquisar.");
        for (int i = 0; i < livros.size(); i++) {
            if (livroPesquisaTitulo.equalsIgnoreCase(livros.get(i).getTitulo())) {
                JOptionPane.showMessageDialog(null, "Livro presente no acervo!");
                livros.get(i).exibirLivro();
            }
            else{
                JOptionPane.showMessageDialog(null, "Livro não encontrado no acervo!");
            }
        }
    }//GEN-LAST:event_pesquisarTituloBotaoActionPerformed

    private void renovarEmprestimoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renovarEmprestimoBotaoActionPerformed
        IDEmprVerifica = JOptionPane.showInputDialog(null, "Insira o ID do empréstimo que deseja renovar.");
        for(int i = 0; i<emprestimos.size(); i++){
            if(IDEmprVerifica.equals(emprestimos.get(i).getIDEmprestimo())){
                emprestimos.get(i).setDataNovaVencimento(dataVencimento.plusDays(7));
                JOptionPane.showMessageDialog(null, "Empréstimo renovado com sucesso!");
            }
        }
    }//GEN-LAST:event_renovarEmprestimoBotaoActionPerformed

    private void pesquisarAutorBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAutorBotaoActionPerformed

        livroPesquisaAutor = JOptionPane.showInputDialog(null, "Insira o autor que deseja pesquisar.");
        for (int i = 0; i < livros.size(); i++) {
            if (livroPesquisaAutor.equalsIgnoreCase(livros.get(i).getAutor())) {
                System.out.println(livros.get(i).getTitulo());
                JOptionPane.showMessageDialog(null, "Autor presente no acervo!");
                livros.get(i).exibirLivro();
            }
        }
    }//GEN-LAST:event_pesquisarAutorBotaoActionPerformed

    private void reservarLivroBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarLivroBotaoActionPerformed

        IDlivroReserva = JOptionPane.showInputDialog(null, "Insira o ID do livro que deseja realizar a reserva.");
        senhaVerifica = JOptionPane.showInputDialog(null, "Insira sua senha: ");
        for(int i = 0; i<usuarios.size(); i++){
            for(int j = 0; j<livros.size(); j++){
                if(senhaVerifica.equals(usuarios.get(i).getSenha())){
                    if(IDlivroReserva.equals(livros.get(j).getIDLivro())){
                        for(int y=0; y<livros.get(j).getExemplares().size(); y++){
                            if(!((Exemplar) livros.get(j).getExemplares().get(y)).getReservado()){
                                ((Exemplar) livros.get(i).getExemplares().get(y)).setReservado(true);
                                IDUsuarioReserva = usuarios.get(i).getIDUsuario();
                                ((Exemplar) livros.get(i).getExemplares().get(y)).setIDUsuarioReserva(IDUsuarioReserva);
                                JOptionPane.showMessageDialog(null, "Reserva realizada com sucesso!");
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Todos os exemplares já estão reservados!");
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Livro não encontrado no acervo!");
                    }
                }
                JOptionPane.showMessageDialog(null, "Senha incorreta!");
            }
        }
    }//GEN-LAST:event_reservarLivroBotaoActionPerformed

    private void realizarEmprestimoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarEmprestimoBotaoActionPerformed
        IDLivroEmpr = JOptionPane.showInputDialog(null, "Insira o ID do livro que deseja realizar o empréstimo.");
        senhaVerifica = JOptionPane.showInputDialog(null, "Insira sua senha: ");
        for(int i = 0; i<usuarios.size(); i++){
            for(int j = 0; j<livros.size(); j++){
                if(senhaVerifica.equals(usuarios.get(i).getSenha())){
                    if(IDLivroEmpr.equals(livros.get(j).getIDLivro())){
                        for(int y=0; y<livros.get(j).getExemplares().size(); y++){
                            if(!((Exemplar) livros.get(j).getExemplares().get(y)).getReservado() && !((Exemplar) livros.get(j).getExemplares().get(y)).getEmprestado()){
                                ((Exemplar) livros.get(i).getExemplares().get(y)).setEmprestado(true);
                                IDEmprestimo = JOptionPane.showInputDialog(null, "Insira o ID do empréstimo.");
                                dataVencimento = LocalDate.now().plusDays(7);
                                IDUsuarioEmpr = usuarios.get(i).getIDUsuario();
                                Emprestimo novoEmprestimo = new Emprestimo(dataVencimento, IDEmprestimo, IDUsuarioEmpr);
                                emprestimos.add(novoEmprestimo);
                                JOptionPane.showMessageDialog(null, "Empréstimo realizado com sucesso!");
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Todos os exemplares já estão reservados ou já estão emprestados...!");
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Livro não encontrado no acervo!");
                    }
                }
                else{
                JOptionPane.showMessageDialog(null, "Senha incorreta!");
                }
            }
        }
    }//GEN-LAST:event_realizarEmprestimoBotaoActionPerformed

    private void cancelarReservaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarReservaBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarReservaBotaoActionPerformed

    private void cancelarEmprestimoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEmprestimoBotaoActionPerformed
        senhaVerifica = JOptionPane.showInputDialog(null, "Insira a sua senha.");
        for(int i = 0; i<usuarios.size(); i++){
            for(int j = 0; i<emprestimos.size(); j++){
                if(senhaVerifica.equals(usuarios.get(i).getSenha()) && emprestimos.get(j).getIDUsuarioEmpr().equals(usuarios.get(i).getIDUsuario())){
                    for(int y = 0; y<livros.size(); y++){
                        for(int l = 0; l<livros.get(y).getExemplares().size(); l++){
                            livros.get(y).getExemplares().get(l).setEmprestado(false);
                            JOptionPane.showMessageDialog(null, "Empréstimo cancelado com sucesso.");
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Senha incorreta ou não há empréstimos para serem cancelados.");
                }
            }
        }
    }//GEN-LAST:event_cancelarEmprestimoBotaoActionPerformed

    private void pesquisarGeneroBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarGeneroBotaoActionPerformed
        livroPesquisaGenero = JOptionPane.showInputDialog(null, "Insira o gênero literário que deseja pesquisar.");
        for (int i = 0; i < livros.size(); i++) {
            if (livroPesquisaTitulo.equalsIgnoreCase(livros.get(i).getGenero())) {
                JOptionPane.showMessageDialog(null, "Gênero literário presente no acervo!");
                livros.get(i).exibirLivro();
            }
            else{
                JOptionPane.showMessageDialog(null, "GÊnero literário não encontrado no acervo!");
            }
        }
    }//GEN-LAST:event_pesquisarGeneroBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalPosLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalPosLogin().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarLivroBotao;
    private javax.swing.JButton cancelarEmprestimoBotao;
    private javax.swing.JButton cancelarReservaBotao;
    private javax.swing.JButton pesquisarAutorBotao;
    private javax.swing.JButton pesquisarGeneroBotao;
    private javax.swing.JButton pesquisarTituloBotao;
    private javax.swing.JButton realizarEmprestimoBotao;
    private javax.swing.JButton renovarEmprestimoBotao;
    private javax.swing.JButton reservarLivroBotao;
    private javax.swing.JLabel tituloInterface;
    // End of variables declaration//GEN-END:variables
}
